add the news application
izzett222/react-news pull request #1
Opened 2023-03-17 14:10 UTC by izzett222

2023-04-03 07:46 UTC, hirwaaldo1 commented on tailwind.config.js
> +    "./src/**/*.{js,jsx,ts,tsx}",
remove ts and tsx extensions because you didn't use any typescript.

2023-04-03 07:46 UTC, hirwaaldo1 commented on src/components/Home.jsx
> +          onClick={() => {}}
I think this event is not needed, you can remove it if it's possible.

2023-04-03 07:46 UTC, hirwaaldo1 commented on src/components/Article.jsx
> +      <Back onClick={viewTrending} />
This is a bit confusing because we don't know whether it's a prop or an event. 
My suggestion is to make it an event if possible.

2023-04-03 07:46 UTC, hirwaaldo1 commented on src/components/Article.jsx
> +        <img src={src} className="w-full aspect-[5/2] object-cover" alt="" />
As you may know, the image is coming from an API, which means that sometimes the image may not load. That's why it's important to fill in the 'alt' attribute.

2023-04-03 07:47 UTC, hirwaaldo1 requested changes
You did a great job 👌, but if you make a few changes, it could be even better.

2023-04-04 06:23 UTC, Ntwali-Josue approved these changes

2023-04-04 09:22 UTC, hirwaaldo1 approved these changes

2023-05-04 08:59 UTC, merged